---
# File: roles/firefox_de/tasks/main.yml

- name: "load the Firefox DE installation's variables"
  include_vars:
    file: "firefox_de.yml"
  tags:
  - "firefox-de"

- name: "download and install {{ title }}"
  include: "../../install_from_archive.yml"
  tags:
  - "firefox-de"
    